In [11]:
import tensorflow.keras as keras
(xtrain, ytrain), (xtest, ytest) = keras.datasets.fashion_mnist.load_data()

In [2]:
print(xtrain.shape)
print(ytrain.shape)
print(xtest.shape)
print(ytest.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)

In [10]:
ytrain[100]

8

In [12]:
xtrain[100].reshape(28,28)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,  18,
        107, 119, 103,   9,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  99, 155,
        113,  61, 118, 173, 117,   0,   0,   3,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   1,   0, 110, 136,   0,
          0,   0,   0,   0, 167, 159,   0,   0,   2,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   1,   0,   6,   0,  72, 147,   0,   0,
          5,   0,   2,   0,   0, 174, 118,   0,   5,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   1,   5,   0,   0, 174,   4,   0,   4,
          0,   0,   0,   0,   0,   0, 204,  44,   0,   4,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   8,   0, 125, 128,   0,   9,   0,
          0,   0,   0,   0,   2,   0, 107, 152,   0,   6,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 184,   9,   0,   4,   0,
          0,   0,   0,   0,   2,   0,   0, 190,   0,   0,   2,   0,   0,
          0,   0],
       [  0,   0,   0,   1,   0,   2,   0,  73, 158,   0,   0,   0,   0,
          1,   0,   0,   0,   0,   4,   0, 157,  79,   0,   3,   1,   0,
          0,   0],
       [  0,   0,   2,   5,   1,   0,   0, 157,  98,   0,   2,   0,   0,
          1,   0,   0,   0,   0,   5,   0, 121, 145,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 231,  84,   0,   2,   1,   1,
          0,   0,   0,   0,   0,   1,   0,  92, 223,  16,   0,   7,   4,
          1,   0],
       [  0,   0,   0,   0,   0,   0,  38, 183,  81,   0,   0,   0,   2,
          2,   1,   2,   1,   0,   1,   0, 120, 226,  57,   0,   0,   0,
          0,   0],
       [  0,   0, 173, 216, 193, 213, 183, 164, 167,  98,  16,   0,   0,
          0,   0,   0,   0,   0,   0,   0, 107, 141, 111,  91,  90, 108,
         50,   0],
       [  0,   0, 185, 221, 217, 210, 202, 222, 200, 206, 202, 204, 109,
         27,  12,  17,  61, 136, 180, 221, 202, 225, 208, 214, 223, 240,
        162,   0],
       [  0,   0, 183, 220, 205, 200, 193, 184, 189, 182, 173, 194, 215,
        216, 205, 207, 207, 195, 185, 194, 194, 203, 212, 183, 193, 211,
        153,   0],
       [  0,   0, 190, 233, 203, 206, 214, 216, 195, 183, 176, 159, 175,
        189, 202, 195, 186, 186, 182, 186, 195, 209, 235, 203, 202, 215,
        136,   0],
       [  0,   0, 180, 228, 201, 202, 188, 183, 178, 192, 186, 181, 181,
        177, 204, 217, 175, 179, 184, 176, 166, 169, 175, 185, 152, 203,
        107,   0],
       [  0,   0, 167, 235, 200, 207, 207, 209, 207, 203, 198, 189, 182,
        178, 186, 189, 178, 192, 197, 195, 192, 185, 184, 205, 187, 255,
         61,   0],
       [  0,   0, 152, 250, 208, 214, 209, 202, 200, 202, 205, 204, 200,
        192, 198, 204, 195, 205, 206, 198, 199, 203, 214, 207, 179, 249,
         55,   0],
       [  0,   0, 126, 255, 211, 215, 210, 206, 203, 203, 203, 206, 204,
        199, 206, 207, 200, 206, 201, 199, 202, 208, 215, 195, 174, 211,
         15,   0],
       [  0,   0, 107, 255, 212, 211, 210, 211, 208, 206, 206, 207, 208,
        208, 217, 214, 205, 206, 204, 208, 211, 211, 220, 197, 182, 225,
          0,   0],
       [  0,   0,  63, 232, 211, 216, 212, 214, 212, 212, 214, 212, 211,
        212, 223, 219, 210, 214, 213, 212, 211, 209, 217, 208, 168, 190,
          0,   0],
       [  0,   0,  14, 255, 218, 221, 215, 218, 218, 217, 215, 213, 211,
        215, 228, 220, 216, 222, 217, 217, 216, 218, 212, 213, 189, 143,
          0,   0],
       [  0,   0,   0, 230, 227, 214, 217, 218, 216, 217, 217, 214, 216,
        222, 226, 218, 218, 220, 219, 218, 217, 218, 217, 215, 216, 113,
          0,   0],
       [  0,   0,   0, 177, 233, 216, 223, 222, 213, 213, 215, 212, 220,
        226, 221, 220, 221, 218, 222, 220, 220, 221, 217, 212, 219,  52,
          0,   0],
       [  0,   0,   0,  10, 223, 222, 220, 211, 213, 215, 220, 222, 226,
        226, 221, 223, 222, 222, 221, 218, 220, 219, 220, 223, 174,   0,
          0,   0],
       [  0,   0,   0,   0, 126, 241, 208, 210, 214, 214, 216, 216, 220,
        220, 214, 213, 212, 212, 210, 215, 217, 218, 215, 236,  42,   0,
          1,   0],
       [  0,   0,   0,   0,   0, 188, 237, 230, 233, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 231, 229, 239, 161,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  63,  95, 108, 105, 100, 103, 104,
        105, 102, 100,  98,  97,  96,  90,  80,  83,  60,   0,   0,   0,
          0,   0]], dtype=uint8)

In [3]:
import numpy as np

xtrain = xtrain.astype('float32') / 255
xtest = xtest.astype('float32') / 255

xtrain = np.reshape(xtrain, (xtrain.shape[0], 28, 28, 1))
xtest = np.reshape(xtest, (xtest.shape[0], 28, 28, 1))

print(xtrain.shape)
print(ytrain.shape)
print(xtest.shape)

(60000, 28, 28, 1)
(60000,)
(10000, 28, 28, 1)

In [4]:
import sqlite3

conn = sqlite3.connect('fashion_mnist.db')

conn.execute('''CREATE TABLE IF NOT EXISTS images
             (id INTEGER PRIMARY KEY AUTOINCREMENT,
             image BLOB NOT NULL,
             label INTEGER NOT NULL);''')

for i in range(xtrain.shape[0]):
    conn.execute('INSERT INTO images (image, label) VALUES (?, ?)',
                [sqlite3.Binary(xtrain[i]), ytrain[i]])

conn.commit()

for i in range(xtest.shape[0]):
    conn.execute('INSERT INTO images (image, label) VALUES (?, ?)',
                [sqlite3.Binary(xtest[i]), ytest[i]])

conn.commit()

In [5]:
import sqlite3
conn = sqlite3.connect('fashion_mnist.db')
cursor = conn.cursor()

cursor.execute('SELECT * FROM images')
rows = cursor.fetchall()

import pandas as pd
data = pd.read_sql_query('SELECT * FROM images', conn)

In [6]:
data

          id                                              image    label
0          1  b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...    b'\t'
1          2  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...  b'\x00'
2          3  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...  b'\x00'
3          4  b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...  b'\x03'
4          5  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...  b'\x00'
...      ...                                                ...      ...
69995  69996  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...    b'\t'
69996  69997  b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...  b'\x01'
69997  69998  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...  b'\x08'
69998  69999  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...  b'\x01'
69999  70000  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...  b'\x05'

[70000 rows x 3 columns]